CREATE OR REPLACE TRIGGER KepFeltoltesTrigger
BEFORE INSERT
ON Kep
FOR EACH ROW
BEGIN
    :NEW.telepules := INITCAP(:NEW.telepules);
END;
/


CREATE OR REPLACE TRIGGER ERTEKELESMODOSITAS
AFTER INSERT OR UPDATE OF CSILLAGOK
ON ERTEKELES
FOR EACH ROW
WHEN (NEW.csillagok <= 0 OR NEW.csillagok > 5)
BEGIN
    RAISE_APPLICATION_ERROR(-20000, 'Hibás érték');
END;
/