INSERT INTO FENYKEPALBUM.SZAVAZAT (NEVEZES_ID, FELHASZNALO_ID) VALUES (1002, 1028);
INSERT INTO FENYKEPALBUM.SZAVAZAT (NEVEZES_ID, FELHASZNALO_ID) VALUES (1002, 1030);
INSERT INTO FENYKEPALBUM.SZAVAZAT (NEVEZES_ID, FELHASZNALO_ID) VALUES (1002, 1110);
INSERT INTO FENYKEPALBUM.SZAVAZAT (NEVEZES_ID, FELHASZNALO_ID) VALUES (1003, 1028);
INSERT INTO FENYKEPALBUM.SZAVAZAT (NEVEZES_ID, FELHASZNALO_ID) VALUES (1003, 1030);